print("twinkle twinkle little star,")
print("how i wonder what you are!")
print("up above the world so high,")
print("like a diamond in the sky.")
print("twinkle twinkle little star,")
print("how i wonder what you are,")
print("when the blazing sun is gone,")
print("when he nothing shines upon,")
print("then you show your little light,")
print("twinkle twinkle all night.")
print("twinkle twinkle little star,")
print("how i wonder what you are")

